### get all typeOfBeers
GET http://localhost:8082/api/typeOfBeers
### get specific typeOfBeer
GET http://localhost:8082/api/typeOfBeers/c4804e0f-769e-4ab9-9ebe-0578fb4f00a2
### get non existent typeOfBeer
GET http://localhost:8082/api/typeOfBeers/c4804e0f-769e-4ab9-9ebe-0578fb4f0000
### create new typeOfBeer
PUT http://localhost:8082/api/typeOfBeers/c4804e0f-769e-4ab9-9ebe-0578fb4f0000
Content-Type: application/json

{
  "typeOfBeerName":"yeast",
  "yearOfInvention": 1929
}
### update typeOfBeer
PATCH http://localhost:8082/api/typeOfBeers/c4804e0f-769e-4ab9-9ebe-0578fb4f0000
Content-Type: application/json

{
  "typeOfBeerName":"yeeest",
  "yearOfInvention": 1930
}

### delete typeOfBeer
DELETE http://localhost:8082/api/typeOfBeers/c4804e0f-769e-4ab9-9ebe-0578fb4f0000
### delete non existent typeOfBeer
DELETE http://localhost:8082/api/typeOfBeers/f79d610b-b14c-4c9c-a229-70fb3fd69222