### get all beers
GET http://localhost:8081/api/beers
### get beer with id
GET http://localhost:8081/api/beers/c4804e0f-769e-4ab9-9ebe-0578fb4f0a12
### get beer not existing
GET http://localhost:8081/api/beers/5b375d8d-0512-4f92-a755-ca5b5dda8223
### get all beers of specified typeOfBeer
GET http://localhost:8081/api/typeOfBeers/c4804e0f-769e-4ab9-9ebe-0578fb4f00a1/beers
### get all beers of non existent typeOfBeer
GET http://localhost:8081/api/typeOfBeers/eb641f55-a18e-45b1-af0f-a3224c05a0aa/beers

### create new beer
PUT http://localhost:8081/api/beers/c4804e0f-769e-4ab9-9ebe-0578fb4f00b1
Content-Type: application/json

{
  "name":"zywiecka",
  "percentage":9,
  "typeOfBeer":"7c326640-9b76-41fa-9889-4d6efb3fdb17"
}

### create new beer in non existent typeOfBeer
PUT http://localhost:8081/api/beers/c4804e0f-769e-4ab9-9ebe-0578fb4f00b3
Content-Type: application/json

{
  "name":"zywiecka ipunia",
  "percentage":100,
  "typeOfBeer":"f79d610b-b14c-4c9c-a229-70fb3fd69444"
}


### get all beers of empty typeOfBeer
GET http://localhost:8081/api/typeOfBeers/c4804e0f-769e-4ab9-9ebe-0578fb4f00a5/beers

### update beer
PATCH http://localhost:8081/api/beers/ae30defb-d7e9-4669-8e25-155ea0430642
Content-Type: application/json

{
  "name": "zywiec2",
  "percentage": 18
}

### update non existent beer
PATCH http://localhost:8081/api/beers/c4804e0f-769e-4ab9-9ebe-0578fb4f0012
Content-Type: application/json

{
  "name": "zywiec4",
  "percentage": 213
}


### delete beer
DELETE http://localhost:8081/api/beers/7eb0ce81-957d-4dc2-b03f-09647044aefd
### delete non existent beer
DELETE http://localhost:8081/api/beers/c4804e0f-769e-4ab9-9ebe-0578fb4f00a1
